builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    extra_files:
      - entrypoint.sh
    image_templates:
      - "julianli/onedump:{{ .Tag }}-arm64"
  - use: buildx
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    extra_files:
      - entrypoint.sh
    image_templates:
      - julianli/onedump
      - "julianli/onedump:{{ .Tag }}-amd64"